// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI905yiTkkwtbFt7GWYwzAjopL7rXkJkA',
    appId: '1:670500221018:web:0a15d7c325c841bfd0e863',
    messagingSenderId: '670500221018',
    projectId: 'flutter-board-c4317',
    authDomain: 'flutter-board-c4317.firebaseapp.com',
    storageBucket: 'flutter-board-c4317.appspot.com',
    measurementId: 'G-XH74NQPEXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNbKb-bF-u_HQD6qLxkposw0yLoPuOR9A',
    appId: '1:670500221018:android:2af221af18abd7e2d0e863',
    messagingSenderId: '670500221018',
    projectId: 'flutter-board-c4317',
    storageBucket: 'flutter-board-c4317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIgq7WdEy0iFOHgs3qHq4vojqrpaQcajI',
    appId: '1:670500221018:ios:90eef0ce3a981461d0e863',
    messagingSenderId: '670500221018',
    projectId: 'flutter-board-c4317',
    storageBucket: 'flutter-board-c4317.appspot.com',
    iosClientId: '670500221018-1d8r39stqntn1fapdlmutvsd1u2ud00a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIgq7WdEy0iFOHgs3qHq4vojqrpaQcajI',
    appId: '1:670500221018:ios:90eef0ce3a981461d0e863',
    messagingSenderId: '670500221018',
    projectId: 'flutter-board-c4317',
    storageBucket: 'flutter-board-c4317.appspot.com',
    iosClientId: '670500221018-1d8r39stqntn1fapdlmutvsd1u2ud00a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpBoard',
  );
}
